// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An api for moving data between a form and the blockchain",
    "title": "Bitmask API",
    "contact": {
      "name": "Hunter Hough",
      "email": "hunter.hough@icf.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "summary": "endpoint to receive answers from the frontend; encrypt and send to blockchain; cache in db",
        "operationId": "postAnswers",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid or not enough inputs.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Too many requests.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Answer": {
      "type": "object",
      "required": [
        "content"
      ],
      "properties": {
        "content": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "number"
        }
      }
    },
    "Question": {
      "type": "object",
      "required": [
        "id",
        "title",
        "content"
      ],
      "properties": {
        "Answer": {
          "$ref": "#/definitions/Answer"
        },
        "content": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Transaction": {
      "type": "object",
      "required": [
        "id",
        "bitmask",
        "amount",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "amount": {
          "type": "number",
          "format": "float64"
        },
        "bitmask": {
          "type": "number",
          "format": "float64"
        },
        "id": {
          "type": "integer",
          "format": "int"
        }
      }
    },
    "Wallet": {
      "type": "object",
      "required": [
        "id",
        "transaction"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "transaction": {
          "$ref": "#/definitions/Transaction"
        }
      }
    }
  }
}`))
}
