// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllTransactionsHandlerFunc turns a function with the right signature into a get all transactions handler
type GetAllTransactionsHandlerFunc func(GetAllTransactionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllTransactionsHandlerFunc) Handle(params GetAllTransactionsParams) middleware.Responder {
	return fn(params)
}

// GetAllTransactionsHandler interface for that can handle valid get all transactions params
type GetAllTransactionsHandler interface {
	Handle(GetAllTransactionsParams) middleware.Responder
}

// NewGetAllTransactions creates a new http.Handler for the get all transactions operation
func NewGetAllTransactions(ctx *middleware.Context, handler GetAllTransactionsHandler) *GetAllTransactions {
	return &GetAllTransactions{Context: ctx, Handler: handler}
}

/*GetAllTransactions swagger:route GET /walletTransactions getAllTransactions

get all records from the database for a particular user

*/
type GetAllTransactions struct {
	Context *middleware.Context
	Handler GetAllTransactionsHandler
}

func (o *GetAllTransactions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllTransactionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
