// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllTransactionsParams creates a new GetAllTransactionsParams object
// with the default values initialized.
func NewGetAllTransactionsParams() GetAllTransactionsParams {
	var ()
	return GetAllTransactionsParams{}
}

// GetAllTransactionsParams contains all the bound params for the get all transactions operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllTransactions
type GetAllTransactionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the password to the wallet
	  In: query
	*/
	PrivateKey *string
	/*Wallet Id
	  In: query
	*/
	WalletID *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetAllTransactionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPrivateKey, qhkPrivateKey, _ := qs.GetOK("privateKey")
	if err := o.bindPrivateKey(qPrivateKey, qhkPrivateKey, route.Formats); err != nil {
		res = append(res, err)
	}

	qWalletID, qhkWalletID, _ := qs.GetOK("walletId")
	if err := o.bindWalletID(qWalletID, qhkWalletID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAllTransactionsParams) bindPrivateKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.PrivateKey = &raw

	return nil
}

func (o *GetAllTransactionsParams) bindWalletID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.WalletID = &raw

	return nil
}
