// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTransactionHandlerFunc turns a function with the right signature into a get transaction handler
type GetTransactionHandlerFunc func(GetTransactionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransactionHandlerFunc) Handle(params GetTransactionParams) middleware.Responder {
	return fn(params)
}

// GetTransactionHandler interface for that can handle valid get transaction params
type GetTransactionHandler interface {
	Handle(GetTransactionParams) middleware.Responder
}

// NewGetTransaction creates a new http.Handler for the get transaction operation
func NewGetTransaction(ctx *middleware.Context, handler GetTransactionHandler) *GetTransaction {
	return &GetTransaction{Context: ctx, Handler: handler}
}

/*GetTransaction swagger:route GET /getRecord getTransaction

get all questions from the database for a particular record for the frontend

*/
type GetTransaction struct {
	Context *middleware.Context
	Handler GetTransactionHandler
}

func (o *GetTransaction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTransactionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
