// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go-DOGE
An api for moving data between a form and dogechain through a bitmask


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: Hunter Hough<hunter.hough@icf.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
