// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An api for moving data between a form and the blockchain",
    "title": "Bitmask API",
    "contact": {
      "name": "Hunter Hough",
      "email": "hunter.hough@icf.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/getRecords": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "get all questions from the database for a particular record for the frontend",
        "operationId": "getRecords",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#definitions/Records"
            }
          },
          "400": {
            "description": "Invalid or not enough inputs.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Too many requests.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "number"
        }
      }
    },
    "Record": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int"
        },
        "question1": {
          "type": "string"
        }
      }
    },
    "Records": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Record"
      }
    },
    "Transaction": {
      "type": "object",
      "required": [
        "hash",
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "number",
          "format": "float64"
        },
        "block_hash": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        },
        "time": {
          "type": "number",
          "format": "integer"
        }
      }
    }
  }
}`))
}
