// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An api for moving data between a form and dogechain through a bitmask",
    "title": "Go-DOGE",
    "contact": {
      "name": "Hunter Hough",
      "email": "hunter.hough@icf.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/getRecords": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "get all records from dogechain by transactionId. Served as an array of transmission_types containing a name and an array of decrypted records",
        "operationId": "getRecords",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#definitions/Transmission_Type"
              }
            }
          },
          "400": {
            "description": "Invalid or not enough inputs.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Too many requests.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "number"
        }
      }
    },
    "Record": {
      "type": "object",
      "properties": {
        "age": {
          "type": "number",
          "format": "integer"
        },
        "case_outbreak_indicator": {
          "type": "string"
        },
        "death": {
          "type": "string"
        },
        "duration": {
          "type": "number",
          "format": "integer"
        },
        "hospitalized": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int"
        },
        "immediate_national_notifiable_condition": {
          "type": "string"
        },
        "pregnancy_status": {
          "type": "string"
        }
      }
    },
    "Transaction": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "format": "float64"
        },
        "block_hash": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        },
        "time": {
          "type": "number",
          "format": "integer"
        }
      }
    },
    "Transmission_Type": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "records": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Record"
          }
        }
      }
    },
    "Wallet": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "transactions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Transaction"
          }
        }
      }
    }
  }
}`))
}
