// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An api for moving data between a form and the blockchain",
    "title": "Bitmask API",
    "contact": {
      "name": "Hunter Hough",
      "email": "hunter.hough@icf.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "endpoint to receive answers from the frontend; encrypt and send to blockchain; cache in db",
        "operationId": "postAnswers",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid or not enough inputs.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Too many requests.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/getRecord": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "get all questions from the database for a particular record for the frontend",
        "operationId": "getTransaction",
        "parameters": [
          {
            "type": "string",
            "description": "Wallet Id",
            "name": "walletId",
            "in": "query"
          },
          {
            "type": "string",
            "description": "the password to the wallet",
            "name": "privateKey",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Id of the transaction",
            "name": "transactionId",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#definitions/Question"
              }
            }
          },
          "400": {
            "description": "Invalid or not enough inputs.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Too many requests.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/walletTransactions": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "get all records from the database for a particular user",
        "operationId": "getAllTransactions",
        "parameters": [
          {
            "type": "string",
            "description": "Wallet Id",
            "name": "walletId",
            "in": "query"
          },
          {
            "type": "string",
            "description": "the password to the wallet",
            "name": "privateKey",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#definitions/Question"
              }
            }
          },
          "400": {
            "description": "Invalid or not enough inputs.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Too many requests.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Answer": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "number"
        }
      }
    },
    "Question": {
      "type": "object",
      "required": [
        "id",
        "title",
        "content"
      ],
      "properties": {
        "Answer": {
          "$ref": "#/definitions/Answer"
        },
        "content": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Transaction": {
      "type": "object",
      "required": [
        "transactionId",
        "bitmask",
        "cost",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "bitmask": {
          "type": "number",
          "format": "float64"
        },
        "cost": {
          "type": "number",
          "format": "float64"
        },
        "dateCreated": {
          "type": "string"
        },
        "fee": {
          "type": "number",
          "format": "number"
        },
        "shortId": {
          "type": "integer",
          "format": "int"
        },
        "transactionId": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "wallets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Wallet"
          }
        }
      }
    },
    "Wallet": {
      "type": "object",
      "required": [
        "id",
        "transactions",
        "privateKey"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "privateKey": {
          "type": "string"
        },
        "transactions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Transaction"
          }
        }
      }
    }
  }
}`))
}
