// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Record record
// swagger:model Record
type Record struct {

	// age
	Age int64 `json:"age,omitempty"`

	// case outbreak indicator
	CaseOutbreakIndicator string `json:"case_outbreak_indicator,omitempty"`

	// death
	Death string `json:"death,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// hospitalized
	Hospitalized string `json:"hospitalized,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// immediate national notifiable condition
	ImmediateNationalNotifiableCondition string `json:"immediate_national_notifiable_condition,omitempty"`

	// pregnancy status
	PregnancyStatus string `json:"pregnancy_status,omitempty"`
}

// Validate validates this record
func (m *Record) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Record) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Record) UnmarshalBinary(b []byte) error {
	var res Record
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
