---
swagger: "2.0"
info:
  title: Go-DOGE
  description: "An api for moving data between a form and dogechain through a bitmask"
  version: 1.0.0
  contact:
    name: Hunter Hough
    email: hunter.hough@icf.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: /v1
schemes:
- http
paths:
  /getRecords:
    get:
      summary: "get all records from dogechain by transactionId. Served as an array of transmission_types containing a name and an array of decrypted records"
      operationId: getRecords
      produces:
        - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#definitions/Transmission_Type"
        400:
          description: Invalid or not enough inputs.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
definitions:
### Backend definitions :: for connecting to dogechain.
# For reference: https://dogechain.info/api/blockchain_api --> -Get transaction
  Wallet:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      name:
        type: "string"
      id:
        type: "string"
      transactions:
        type: "array"
        items:
          $ref: "#/definitions/Transaction"
  Transaction:
    type: "object"
    required:
      - "hash"
      - "amount"
    properties:
      hash:
        type: "string"
      block_hash:
        type: "string"
      time:
        type: "number"
        format: "integer"
      amount:
        type: "number"
        format: "float64"

### Front End definitions, for serving decrypted data
  Transmission_Type:
    type: "object"
    required:
      - "name"
    properties:
      name:
        type: "string"
      records:
        type: "array"
        items:
          $ref: "#/definitions/Record"
  Record:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int"
      pregnancy_status:
        type: "string"
      hospitalized:
        type: "string"
      duration:
        type: "number"
        format: "integer"
      death:
        type: "string"
      age:
        type: "number"
        format: "integer"
      immediate_national_notifiable_condition:
        type: "string"
      case_outbreak_indicator:
        type: "string"

# Generic error
  Error:
    type: "object"
    properties:
      status:
        type: "number"
      message:
        type: "string"