---
swagger: "2.0"
info:
  title: Bitmask API
  description: "An api for moving data between a form and the blockchain"
  version: 1.0.0
  contact:
    name: Hunter Hough
    email: hunter.hough@icf.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: /v1

schemes:
- http
paths:
#  /questions:
#    get:
#      tags:
#        - question
#      summary: "get all questions from the database for the frontend"
#      operationId: getQuestions
#      consumes:
#        - application/json
#      produces:
#        - application/json
#      responses:
#        200:
#          description: "successful operation"
#          schema:
#            type: "array"
#            items:
#              $ref: "#definitions/Question"
#        400:
#          description: Invalid or not enough inputs.
#          schema:
#            $ref: "#/definitions/Error"
#        429:
#          description: Too many requests.
#          schema:
#            $ref: "#/definitions/Error"
  /:
    post:
      summary: "endpoint to receive answers from the frontend; encrypt and send to blockchain; cache in db"
      operationId: postAnswers
      consumes:
        - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            type: string
        400:
          description: Invalid or not enough inputs.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
definitions:
  Wallet:
    type: "object"
    required:
      - "id"
      - "transaction"
    properties:
      id:
        type: "string"
      transaction:
        $ref: "#/definitions/Transaction"
  Transaction:
    type: "object"
    required:
      - "id"
      - "bitmask"
      - "amount"
      - "address"
    properties:
      id:
        type: "integer"
        format: "int"
      bitmask:
        type: "number"
        format: "float64"
      amount:
        type: "number"
        format: "float64"
      address:
        type: "string"
  Error:
    type: "object"
    properties:
      status:
        type: "number"
      message:
        type: "string"
  Question:
    type: "object"
    required:
      - "id"
      - "title"
      - "content"
    properties:
      id:
        type: "integer"
        format: "int"
      title:
        type: "string"
      content:
        type: "string"
      description:
        type: "string"
      Answer:
        $ref: "#/definitions/Answer"
  Answer:
    type: "object"
    required:
      - "content"
    properties:
      id:
        type: "integer"
        format: "int"
      title:
        type: "string"
      content:
        type: "string"
      description:
        type: "string"