swagger: '2.0'
info:
  description: "This is the Swagger specification for the HIV.gov Locator API."
  version: 2.0.18
  title: Locator
  contact:
    name: Alejandro Quesada
    email: alejandro.quesada@icf.com
    url: https://locator.hiv.gov
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: /v2
tags:
  - name: zipcode
    description: "Query providers by zipcode and other inputs."
  - name: location
    description: "Query providers by geohashes and other inputs."
    externalDocs:
      description: Find out more
      url: "http://geohash.co/"
schemes:
  - http
paths:
  /location:
    get:
      tags:
        - location
      summary: "Retrieve providers of a location by longitude, latitude and radius."
      description: ''
      operationId: getProviders
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "longitude"
          in: "query"
          description: "Longitude to query local providers"
          type: "number"
        - name: "latitude"
          in: "query"
          description: "Latitude to query local providers"
          type: "number"
        - name: "radius"
          in: "query"
          description: "Radius to be queried from longitude, latitude in query for local providers"
          required: true
          type: "number"
        - name: "streetAddress1"
          in: "query"
          description: "StreetAddress1 to query local providers."
          type: "string"
        - name: "streetAddress2"
          in: "query"
          description: "StreetAddress2 to query local providers."
          type: "string"
        - name: "City"
          in: "query"
          description: "City to query local providers."
          type: "string"
        - name: "State"
          in: "query"
          description: "State to query local providers."
          type: "string"
        - name: "Country"
          in: "query"
          description: "Country to query local providers."
          type: "string"
        - name: "services"
          in: "query"
          description: "Services to find providers for"
          required: false
          type: "array"
          items:
            type: "string"
            enum:
            - "testing"
            - "housingclinics"
            - "ryanwhite"
            - "mentalhealth"
            - "substanceabuse"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: Invalid or not enough inputs.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
  /location/{geohash}:
    get:
      tags:
        - location
      summary: "Retrieve providers of a location by geohash."
      description: ''
      operationId: getProvidersByGeohash
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "geohash"
          in: "path"
          description: "Geohash of location to by Geospatially Queried"
          required: true
          type: "string"
        - name: "services"
          in: "query"
          description: "Services to find providers for"
          required: false
          type: "array"
          items:
            type: "string"
            enum:
            - "testing"
            - "housingclinics"
            - "ryanwhite"
            - "mentalhealth"
            - "substanceabuse"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: Invalid input.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
  /location/{geohash}/service/{service}:
    get:
      tags:
        - location
      summary: "Retrieve providers of a location by geohash and service type."
      description: ''
      operationId: getProvidersByGeohashAndService
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "geohash"
          in: "path"
          description: "Geohash of location to by geospatially queried"
          required: true
          type: "string"
        - name: "service"
          in: "path"
          description: "Service to find providers for"
          required: true
          type: "string"
          enum:
            - "testing"
            - "housingclinics"
            - "ryanwhite"
            - "mentalhealth"
            - "substanceabuse"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: Invalid input.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
  /location/{geohash}/provider/{id}:
    get:
      tags:
        - location
      summary: "Retrieve providers of a location by geohash and service type."
      description: ''
      operationId: getProvidersByGeohashAndProviderId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "geohash"
          in: "path"
          description: "Geohash of location to by geospatially queried"
          required: true
          type: "string"
        - name: "id"
          in: "path"
          description: "Provider ID to query information for"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: Invalid input or no matching providers.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
  /zipcode/{zipcode}:
    get:
      tags:
        - zipcode
      summary: Retrieve providers of a location by area Zipcode.
      description: ''
      operationId: getProvidersByZipcode
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "zipcode"
          in: "path"
          description: "Zipcode to query locations for"
          required: true
          type: "string"
        - name: "services"
          in: "query"
          description: "Services to find providers for"
          required: false
          type: "array"
          items:
            type: "string"
            enum:
            - "testing"
            - "housingclinics"
            - "ryanwhite"
            - "mentalhealth"
            - "substanceabuse"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: "Invalid zipcode"
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
  /zipcode/{zipcode}/service/{service}:
    get:
      tags:
        - zipcode
      summary: Retrieve providers of a location by zipcode and service type.
      description: ''
      operationId: getProvidersByZipcodeAndService
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "zipcode"
          in: "path"
          description: "Zipcode to query locations for"
          required: true
          type: "string"
        - name: "service"
          in: "path"
          description: "Service to find providers for"
          required: true
          type: "string"
          enum:
            - "testing"
            - "housingclinics"
            - "ryanwhite"
            - "mentalhealth"
            - "substanceabuse"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: Invalid input.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
  /zipcode/{zipcode}/provider/{id}:
    get:
      tags:
        - zipcode
      summary: Retrieve providers of a location by zipcode and service type.
      description: ''
      operationId: getProvidersByZipcodeAndProviderId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "zipcode"
          in: "path"
          description: "Zipcode to query locations for"
          required: true
          type: "string"
        - name: "id"
          in: "path"
          description: "Provider ID to query information for"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Provider"
        400:
          description: Invalid input or no matching providers.
          schema:
            $ref: "#/definitions/Error"
        429:
          description: Too many requests.
          schema:
            $ref: "#/definitions/Error"
      security: []
definitions:
  Provider:
    type: "object"
    required:
      - "type"
      - "id"
      - "attributes"
    properties:
      id:
        type: "string"
      type:
        type: "string"
        description: "Service Type"
      attributes:
        type: "object"
        required:
          - "name"
        properties:
          name:
            type: "string"
          address:
            $ref: "#/definitions/Address"
          contact:
            $ref: "#/definitions/Contact"
          categories:
            type: "array"
            items:
              type: "string"
          languages:
            type: "string"              # languages should be an array
            enum:
              - "en"
              - "es"
          point:
            $ref: "#/definitions/Point"
          updated:
            type: "number"
  Point:
    type: "object"
    required:
      - "latitude"
      - "longitude"
    properties:
      latitude:
        type: "number"
      longitude:
        type: "number"
  Address:
    type: "object"
    required:
      - "zipcode"
    properties:
      streetAddress1:
        type: "string"
      streetAddress2:
        type: "string"
      city:
        type: "string"
      state:
        type: "string"
      country:
        type: "string"
      zipcode:
        type: "string"
  Contact:
    type: "object"
    properties:
      telephone:
        type: "string"
      website:
        type: "string"
      facebook:
        type: "string"
      twitter:
        type: "string"
      instagram:
        type: "string"
      snapchat:
        type: "string"
      other:
        type: "string"
  Error:
    type: "object"
    properties:
      status:
        type: "number"
      message:
        type: "string"
externalDocs:
  description: "Find out more about HIV.gov Locator"
  url: "https://www.hiv.gov/locator"